version : '2'
services:

  cloudserver:
    build:
      context: .
      dockerfile: cloud/Dockerfile
    ports:
      - "8081:8080"
    container_name: cloudserver

  offlineserver:
    build:
      context: .
      dockerfile: offline/Dockerfile
    ports:
      - "8082:8080"
    container_name: offlineserver


